[tool.poetry]
name = "17-allbus-ideaology"
version = "0.1.0"
description = ""
authors = ["Bastian.hundt <bastian.hundt@gmx.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
